### ISSUE TITLE
Optional Gamepad Background Input

### ISSUE THREAD

**Issue by ChristianSilvermoon** [snesrev/smw#11]
### What feature do you want to get added? And how it will work?

In a number of games it is possible to enable a **Background Input** setting so that the game can still be controlled while it is not the currently focused application.

I believe this is possible with SDL2.

This is a really useful feature for multitasking, for example with multiple monitors, so that the keyboard can be used elsewhere quickly, while the gamepad continues to control the game.

**Comment by FitzRoyX** [comment]
> In a number of games it is possible

I can't even find any on google, just a few emulators. Blocking inputs outside of focus is pretty standard behavior. You'd have to wipe every keyboard binding in the ini to avoid conflicts and then have a second person playing mario on a gamepad while you were typing for this to even make a shred of sense.
