### ISSUE TITLE
Audio latency is a little high

### ISSUE THREAD

**Issue by TheGag96** [snesrev/smw#12]
### Describe your bug here. And how to reproduce it.

(First of all, holy cow, this project is surreal... My brain is not used to instant load times in this game!)

Playing for a bit, I'm noticing that the audio latency is a little higher than you'd expect (~80+ ms?) playing this. Just a guess, is the buffer you're using for your audio sized too conservatively? 

### What is your build target?

Linux

**Comment by FitzRoyX** [comment]
There is a setting for the buffer size in smw.ini which defaults to 512, don't you see it? I've set it much lower without problems. Also, if you're on PulseAudio, that is known to be high latency.

**Comment by TheGag96** [comment]
Am I missing something? `g_config.audio_samples` isn't used anywhere after being read from the config. I'm using Pipewire, so anything with Pulse shouldn't be a problem lol. (Even in Pulse, you could at least tweak the buffer sizes to get latency down, but the defaults *are* stupid high...)
