### ISSUE TITLE
Audio has aliasing issues?

### ISSUE THREAD

**Issue by TheGag96** [snesrev/smw#13]
### Describe your bug here. And how to reproduce it.

The audio sounds a tad off from what you'd hear from an emulator, whether it's mixing at 32 kHz or some higher sample rate. I could be wrong, but it sounds somewhat like aliasing issues (audio isn't being resampled to the target sample rate in a smooth way).

### What is your build target?

Linux

**Comment by FitzRoyX** [comment]
I hear the slight difference as well (someone described jumps as tinny) and it's either one of two things. Either the SDL resampler is forcibly active even at 32000 freq. Or the LakeSNES DSP emulation is not quite as accurate as the bit-perfect DSP emulation in bsnes/ares.
