### ISSUE TITLE
On Arch Linux the build is broken with the latest SDL2

### ISSUE THREAD

**Issue by xcom169** [snesrev/smw#19]
cc -c -O2 -fno-strict-aliasing -Werror  -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 -I. src/main.c -o src/main.o
src/main.c: In function ‘main’:
src/main.c:389:10: error: lvalue required as left operand of assignment
  389 |     kRom = ReadWholeFile(argv[0], &size);
      |          ^
make: *** [Makefile:25: src/main.o] Error 1

**Comment by snesrev** [comment]
Fixed in main
