### ISSUE TITLE
Immediate Crash with SMB1

### ISSUE THREAD

**Issue by godreborn** [snesrev/smw#7]
I just tried the smb1 build, but when trying to load smb1, it does this:

![image](https://github.com/snesrev/smw/assets/13548481/055eff93-35ce-4d52-90d6-fac7bf199376)

**Comment by DaBanana64** [comment]
Have you tried compiling it again?

**Comment by godreborn** [comment]
yes, the problem was that the python script got corrupted with git clone, so a git pull fixed the problem.  the game now works.

**Comment by DaBanana64** [comment]
Ok you can close the issue now.

**Comment by godreborn** [comment]
right on.  thanks again.
